// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzftmjtjrejbfpqrheza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZnRtanRqcmVqYmZwcXJoZXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTk5MDksImV4cCI6MjA3MjQ5NTkwOX0.ydxmDXbLlO4tTU3d9Qglvu_me6_DTiHkC6oDPmWIAyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});